# Generated by Django 4.2.11 on 2024-04-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vystaveni', models.DateField(auto_now_add=True)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zaplaceno', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefonni_cislo', models.CharField(max_length=15)),
                ('adresa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_pokoje', models.CharField(max_length=10, unique=True)),
                ('typ_pokoje', models.CharField(choices=[('1L', 'Jednolůžkový'), ('2L', 'Dvoulůžkový'), ('AP', 'Apartmá')], default='1L', max_length=2)),
                ('popis', models.TextField()),
                ('cena_za_noc', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hodnoceni', models.IntegerField()),
                ('datum_zverejneni', models.DateField(auto_now_add=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_prijezdu', models.DateField()),
                ('datum_odjezdu', models.DateField()),
                ('celkova_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.klient')),
                ('pokoj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.pokoj')),
            ],
        ),
        migrations.CreateModel(
            name='Sluzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Uklid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_uklidu', models.DateField()),
                ('pokoj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.pokoj')),
            ],
        ),
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('pozice', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefonni_cislo', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='uklid',
            name='zamestnanec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo_app.zamestnanec'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='rezervace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.rezervace'),
        ),
    ]
