# Generated by Django 5.0.6 on 2024-06-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_faktura_klient_pokoj_recenze_rezervace_sluzba_uklid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='rezervace',
        ),
        migrations.RemoveField(
            model_name='recenze',
            name='klient',
        ),
        migrations.DeleteModel(
            name='Sluzba',
        ),
        migrations.RemoveField(
            model_name='uklid',
            name='pokoj',
        ),
        migrations.RemoveField(
            model_name='uklid',
            name='zamestnanec',
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name': 'Klient', 'verbose_name_plural': 'Klienti'},
        ),
        migrations.AlterModelOptions(
            name='pokoj',
            options={'verbose_name': 'Pokoj', 'verbose_name_plural': 'Pokoje'},
        ),
        migrations.AlterModelOptions(
            name='rezervace',
            options={'verbose_name': 'Rezervace', 'verbose_name_plural': 'Rezervace'},
        ),
        migrations.AddField(
            model_name='pokoj',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='pokoj_obrazky/', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='adresa',
            field=models.CharField(max_length=50, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='jmeno',
            field=models.CharField(max_length=100, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='prijmeni',
            field=models.CharField(max_length=100, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefonni_cislo',
            field=models.CharField(max_length=15, verbose_name='Telefonní číslo'),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='cena_za_noc',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena za noc'),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='cislo_pokoje',
            field=models.CharField(max_length=10, unique=True, verbose_name='Číslo pokoje'),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='popis',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='typ_pokoje',
            field=models.CharField(choices=[('1L', 'Jednolůžkový'), ('2L', 'Dvoulůžkový'), ('AP', 'Apartmá')], default='1L', max_length=2, verbose_name='Typ pokoje'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='celkova_cena',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Celková cena'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='datum_odjezdu',
            field=models.DateField(verbose_name='Datum odjezdu'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='datum_prijezdu',
            field=models.DateField(verbose_name='Datum příjezdu'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.klient', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='rezervace',
            name='pokoj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.pokoj', verbose_name='Pokoj'),
        ),
        migrations.DeleteModel(
            name='Faktura',
        ),
        migrations.DeleteModel(
            name='Recenze',
        ),
        migrations.DeleteModel(
            name='Uklid',
        ),
        migrations.DeleteModel(
            name='Zamestnanec',
        ),
    ]
