# Generated by Django 5.0.6 on 2024-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_faktura_rezervace_remove_recenze_klient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokoj',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Obrázek'),
        ),
    ]
