# Generated by Django 5.0.6 on 2024-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_pokoj_obrazek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokoj',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='../', verbose_name='Obrázek'),
        ),
    ]
